from fury_api.lib.exceptions import FuryAPIError

__all__ = [
    "EarthquakeError",
]


class EarthquakeError(FuryAPIError):
    pass
